import './globals.css'
import type { Metadata } from 'next'
import {Bellefair} from 'next/font/google'
import { Navbar } from '@/components/NavBar'

const bellefair = Bellefair({ subsets: ['latin'], weight: '400', display: 'swap' })


export const metadata: Metadata = {
  title: 'Space Travel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={bellefair.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
